const books={
  'field-guide':{label:'FIELD GUIDE / FED-HUB 001',title:'The Muse Field Guide',intro:'How to build a creative practice that gets stranger, sharper, and more human with AI in the room.',body:`<h3>Begin with a better question</h3><p>The first instinct is to ask a machine for an answer. The more interesting move is to ask it for a new angle on the question itself.</p><blockquote>“Treat intelligence as a material, not a destination.”</blockquote><p>This field guide is a set of small practices for writers, designers, founders, and curious people who want AI to widen their attention—not replace it.</p><h3>Three moves to try</h3><ul><li><strong>Invert the brief.</strong> Ask the model to argue for the opposite of your current plan.</li><li><strong>Invite the weird draft.</strong> Request the version that is too specific, too poetic, or too early to be useful.</li><li><strong>Keep the human edit.</strong> Your taste is not a bottleneck. It is the point of the loop.</li></ul>`},
  'synthetic-signal':{label:'SIGNAL REPORT / FED-HUB 002',title:'Synthetic Signal',intro:'Reading the new patterns in work, culture, and authorship before they become obvious.',body:`<h3>The signal is not the output</h3><p>Every generation leaves a trace. When machines can produce plausible work at the speed of thought, the scarce resource becomes discernment: knowing what deserves more time.</p><blockquote>“The future will belong to people who can recognize meaning before it has a market.”</blockquote><p>Synthetic Signal looks at the emerging creative economy through five lenses: speed, taste, trust, provenance, and the return of the small studio.</p><h3>A field test</h3><ul><li>What did the machine make easier?</li><li>What did it make less visible?</li><li>Where did your own judgment become more important, not less?</li></ul>`},
  'quiet-machines':{label:'INNER MANUAL / FED-HUB 003',title:'Quiet Machines',intro:'A slower, gentler way to collaborate with intelligence that never gets tired.',body:`<h3>Make a room for thought</h3><p>Productivity is not the only reason to work with a machine. Sometimes the gift is a patient surface for thinking out loud, a place where half-formed ideas can become audible.</p><blockquote>“Not every useful conversation has to end in a deliverable.”</blockquote><p>Quiet Machines is an inner manual for using AI without turning every moment into a performance. It includes rituals for reflection, disagreement, and the beautiful pause between prompts.</p><h3>The quiet protocol</h3><ul><li>Start with the thing you cannot yet phrase.</li><li>Ask for questions before solutions.</li><li>Leave one answer unfinished on purpose.</li></ul>`}
};
const modal=document.getElementById('modal'), content=document.getElementById('modalContent');
function openModal(html){content.innerHTML=html;modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.style.overflow=''}
document.querySelectorAll('[data-close]').forEach(el=>el.addEventListener('click',closeModal));
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
document.querySelectorAll('[data-scroll]').forEach(el=>el.addEventListener('click',()=>document.querySelector(el.dataset.scroll)?.scrollIntoView({behavior:'smooth'})));
document.querySelectorAll('[data-open-book]').forEach(button=>button.addEventListener('click',()=>{const book=books[button.dataset.openBook];openModal(`<div class="reader-content"><span class="modal-label">${book.label}</span><h2>${book.title}</h2><p class="large-copy">${book.intro}</p>${book.body}</div>`)}));
document.querySelectorAll('[data-open]').forEach(el=>el.addEventListener('click',e=>{e.preventDefault();if(el.dataset.open==='manifesto')openModal(`<span class="modal-label">FED-HUB / A SMALL MANIFESTO</span><h2>Make the<br><em>invisible</em><br>legible.</h2><p>We believe AI should make room for more human attention, not less. FED-HUB is an AI-agent field library for people who want to think with machines without becoming machine-shaped.</p><p>Our books are small on purpose. They are meant to be read in one sitting, carried into a real project, and returned to when the obvious answer starts to feel too easy.</p><blockquote>“The point is not to outsource wonder. It is to give wonder a better instrument.”</blockquote>`);if(el.dataset.open==='dispatch')openModal(`<span class="modal-label">DISPATCH 014 / 06 MIN READ</span><h2>The best AI workflow is a <em>change</em> of mind.</h2><p>There is a familiar story about AI: prompt well, automate more, move faster. But speed is only one dimension of capability. The more consequential shift is perceptual.</p><p>A machine can help you notice the assumptions packed inside your first idea. It can show you the shape of an adjacent possibility. It can make ten bad drafts cheap enough that the good one has somewhere to come from.</p><blockquote>Use the tool to make the room larger, not the person smaller.</blockquote>`)}));
document.querySelectorAll('.filter').forEach(filter=>filter.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(f=>f.classList.remove('active'));filter.classList.add('active');document.querySelectorAll('.book-card').forEach(card=>card.classList.toggle('is-hidden',filter.dataset.filter!=='all'&&card.dataset.category!==filter.dataset.filter))}));
const toast=document.createElement('div');toast.className='toast';document.body.appendChild(toast);document.getElementById('copyPrompt').addEventListener('click',async()=>{const text='Describe this like it knows something I don’t.';try{await navigator.clipboard.writeText(text)}catch(e){}toast.textContent='Prompt copied to your pocket';toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200)});
const orb=document.getElementById('cursorOrb');window.addEventListener('pointermove',e=>{orb.style.left=e.clientX+'px';orb.style.top=e.clientY+'px'});document.querySelectorAll('a,button').forEach(el=>{el.addEventListener('mouseenter',()=>{orb.style.width='38px';orb.style.height='38px';orb.style.background='rgba(238,166,93,.25)'});el.addEventListener('mouseleave',()=>{orb.style.width='20px';orb.style.height='20px';orb.style.background='transparent'})});

const uploadForm=document.getElementById('uploadForm');
const uploadInput=document.getElementById('bookUpload');
const uploadResult=document.getElementById('uploadResult');
if(uploadForm){const approved=window.FED_HUB_APPROVED_USER===true||new URLSearchParams(location.search).get('approved')==='1';const panel=uploadForm.querySelector('.dropzone');const button=uploadForm.querySelector('button');const label=document.getElementById('approvalLabel');const note=document.getElementById('approvalNote');if(!approved){uploadForm.classList.add('is-locked');uploadInput.disabled=true;button.disabled=true;label.textContent='APPROVED USER ONLY';note.textContent='Upload lane locked';panel.setAttribute('aria-disabled','true')}else{label.textContent='APPROVED SESSION';note.textContent='Upload lane open'}uploadForm.addEventListener('submit',e=>{e.preventDefault();if(!approved){uploadResult.textContent='Upload unavailable: an approved FED-HUB session is required.';return}const file=uploadInput.files[0];if(!file){uploadResult.textContent='Choose a Markdown manuscript first.';return}if(!/\.(md|markdown|txt)$/i.test(file.name)){uploadResult.textContent='FED-HUB accepts Markdown manuscripts only.';return}uploadResult.textContent=`${file.name} is staged for the approved FED-HUB upload lane — no second approval required.`;uploadForm.classList.add('uploaded')})}

const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.style.opacity='1';entry.target.style.transform='translateY(0)';revealObserver.unobserve(entry.target)}}),{threshold:.08});document.querySelectorAll('.book-card,.dispatch,.ritual-card,.manifesto-grid').forEach((el,i)=>{el.style.opacity='0';el.style.transform='translateY(18px)';el.style.transition=`opacity .7s ease ${i*80}ms, transform .7s cubic-bezier(.22,1,.36,1) ${i*80}ms`;revealObserver.observe(el)});
